#!/bin/sh
#
# Container start-up: turn environment variables into the two files nginx and the browser read.
#
# This is what makes the image environment-agnostic. The bundle is built once with the YAML defaults
# baked in; here, at start-up, a deployment may point it at a different API without a rebuild:
#
#   docker run -e APP_API_BASE_URL=https://api.example.com/api/v1 fin-dashboard-ui
#
set -eu

API_UPSTREAM="${API_UPSTREAM:-http://api:8080}"
SERVER_PORT="${SERVER_PORT:-8080}"

HTML_DIR=/usr/share/nginx/html
CONFIG_JS="${HTML_DIR}/config.js"

# ---- nginx configuration ------------------------------------------------------------------------
# Only the two placeholders are substituted: nginx's own `$host`, `$uri` and friends must survive.
envsubst '${API_UPSTREAM} ${SERVER_PORT}' \
  < /etc/nginx/templates/nginx.conf.template \
  > /etc/nginx/conf.d/default.conf

# ---- Runtime application configuration ----------------------------------------------------------
# Emitted as a partial object: whatever is not named here keeps the value baked in at build time from
# config/config.production.yaml, and src/config/app-config.ts deep-merges the two.
#
# `printf` rather than `echo -e` because the shell here is BusyBox ash, where `echo -e` is not portable.
json_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

{
  printf '/* Generated by docker/entrypoint.sh at container start. Do not edit. */\n'
  printf 'window.__APP_CONFIG__ = {\n'

  if [ -n "${APP_API_BASE_URL:-}" ]; then
    printf '  api: { baseUrl: "%s" },\n' "$(json_escape "${APP_API_BASE_URL}")"
  fi

  if [ -n "${APP_WS_URL:-}" ]; then
    printf '  websocket: { url: "%s" },\n' "$(json_escape "${APP_WS_URL}")"
  fi

  if [ -n "${APP_ENVIRONMENT_LABEL:-}" ]; then
    printf '  app: { environmentLabel: "%s" },\n' "$(json_escape "${APP_ENVIRONMENT_LABEL}")"
  fi

  if [ -n "${APP_LOG_LEVEL:-}" ]; then
    printf '  logging: { level: "%s" },\n' "$(json_escape "${APP_LOG_LEVEL}")"
  fi

  printf '};\n'
} > "${CONFIG_JS}"

echo "fin-dashboard-ui: serving on :${SERVER_PORT}, proxying /api and /ws to ${API_UPSTREAM}"

# `exec` so nginx becomes PID 1 and receives SIGTERM directly — otherwise `docker stop` waits out the
# full timeout before killing the container.
exec "$@"
